name: monthly-build-deploy


on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        accountnumber: [{{ secrets.AWS_ACCOUNT_VOTESHIELD }}, {{ secrets.AWS_ACCOUNT_DEV }}]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.accountnumber }}.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          context: pritunl-zero-ecs-bastion
          push: true
          tags: ${{ matrix.accountnumber }}.dkr.ecr.us-east-1.amazonaws.com/pritunl-zero-ecs-bastion:latest